### ISSUE TITLE
postgrest docker container crash loop with error: "Error in config Malformed proxy uri"

### ISSUE THREAD

**Issue by KamranAzeem** [PostgREST/postgrest-docs#446]
Hello. 
I am using the install and run instructions from https://postgrest.org/en/stable/tutorials/tut0.html .

I am using docker compose to bring up postgrest and swagger, as explained in the link above. My setup is simple. I have a small test instance at a cloud provider, as: `test-vm.aclab.online` . 

Postgresql 13 runs in a separate compose file, connected on the same docker network "services-network".
 
My docker-compose file for postgrest and swagger looks like this:

```
version: "3"
services:
  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - /home/containers-secrets/postgrest/postgrest.env
    environment:
      - TZ=Europe/Oslo
      - PGRST_DB_SCHEMA=public
      - PGRST_OPENAPI_SERVER_PROXY_URI="http://127.0.0.1:3000"

    networks:
      - services-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/

    networks:
      - services-network

networks:
  services-network:
    external: true
```

postgrest.env file looks like this:

```
PGRST_DB_URI=postgres://authenticator:secret-password@postgres-13:5432/testappdb
PGRST_DB_ANON_ROLE=web_anon
```

When I start postgrest, I see the following errors in the log and postgrest keep restarting.

```
[root@test-nginx-vm postgrest]# docker-compose -f docker-compose.server.yml up -d
Creating postgrest_postgrest_1 ... done
Creating postgrest_swagger_1   ... done
[root@test-nginx-vm postgrest]#

[root@test-nginx-vm postgrest]# docker-compose -f docker-compose.server.yml logs -f
Attaching to postgrest_postgrest_1, postgrest_swagger_1
postgrest_1  | postgrest: FatalError {fatalErrorMessage = "Error in config Malformed proxy uri, a correct example: https://example.com:8443/basePath"}
postgrest_1  | postgrest: FatalError {fatalErrorMessage = "Error in config Malformed proxy uri, a correct example: https://example.com:8443/basePath"}
^CERROR: Aborting.
[root@test-nginx-vm postgrest]# 
```

There is not much documentation about the particular directive/ENV-variable:  `PGRST_OPENAPI_SERVER_PROXY_URI` . 

Commenting out the directive in postgrest, brings up postgrest instance and I can access it over the internet on port 3000. 
![Screenshot from 2021-10-19 18-26-02](https://user-images.githubusercontent.com/4216369/137953141-f8adb2df-dece-4ab6-8b4b-7d9b049d9f49.png)

Accessing swagger over internet using my browser shows the following:
![Screenshot from 2021-10-19 18-25-50](https://user-images.githubusercontent.com/4216369/137952535-4616f2f7-08e5-4324-891b-0fb753918a95.png)

Any help will be appreciated. Thanks.

**Comment by KamranAzeem** [comment]
I removed the double quotation marks around the value I specified for PGRST_OPENAPI_SERVER_PROXY_URI, and suddenly it starts to work.

The documentation should be updated to remove this error. The value of the PGRST_OPENAPI_SERVER_PROXY_URI should not be enclosed in quotation marks. (that is what I understood).


## Here is my new docker-compose file (again):
```
[root@test-nginx-vm postgrest]# grep -v \# docker-compose.server.yml 
version: "3"

services:

  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - /home/containers-secrets/postgrest/postgrest.env 
    environment:
      - TZ=Europe/Oslo
      - PGRST_DB_SCHEMA=public
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://test-vm.aclab.online:3000
      - PGRST_DB_ANON_ROLE=web_anon

    networks:
      - services-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://test-vm.aclab.online:3000/

    networks:
      - services-network

networks:
  services-network:
    external: true
[root@test-nginx-vm postgrest]# 
```

## I can see postgrest working now:
```
[root@test-nginx-vm postgrest]# docker-compose -f docker-compose.server.yml up -d ; docker-compose -f docker-compose.server.yml  logs -f
Creating postgrest_postgrest_1 ... done
Creating postgrest_swagger_1   ... done
Attaching to postgrest_postgrest_1, postgrest_swagger_1
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Attempting to connect to the database...
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Connection successful
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Listening on port 3000
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Config re-loaded
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Listening for notifications on the pgrst channel
postgrest_1  | 20/Oct/2021:09:52:33 +0000: Schema cache loaded
^CERROR: Aborting.
[root@test-nginx-vm postgrest]#
```

```
[root@test-nginx-vm postgrest]# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS         PORTS                                                                      NAMES
dfecf99e8692   postgrest/postgrest       "/bin/postgrest"         7 minutes ago   Up 7 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                  postgrest_postgrest_1
79542d29f7cb   swaggerapi/swagger-ui     "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes   80/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                          postgrest_swagger_1
ed04c6106234   postgres-13_postgres-13   "docker-entrypoint.s…"   22 hours ago    Up 22 hours    0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                  postgres-13_postgres-13_1
[root@test-nginx-vm postgrest]# 
```

## postgrest screenshot:
![Screenshot from 2021-10-20 11-57-38](https://user-images.githubusercontent.com/4216369/138072652-21986990-8094-410d-9cf2-f0bf3b3ca5db.png)


## Swagger screenshot:
![Screenshot from 2021-10-20 12-00-40](https://user-images.githubusercontent.com/4216369/138072728-b96cb6c8-3718-4757-ac94-774b137bd1c3.png)

Thanks!
